#!/usr/bin/env npx tsx
// Generates demo seed SQL for InboxAngel.
//
// Usage:
//   npm run seed:local    — seed local D1
//   npm run seed:remote   — seed remote D1
//   npm run unseed:local  — wipe demo data locally
//   npm run unseed:remote — wipe demo data remotely
//
// Creates three demo domains that tell a story:
//   acme.com       — enforced (reject, 96% pass) — the goal
//   getacme.com    — transitioning (quarantine, 78% pass) — in progress
//   acme-mail.com  — unprotected (none, 44% pass) — needs action
//
// 30 days of daily reports from 4 real-world reporting orgs.

const NOW = Math.floor(Date.now() / 1000);
const DAY = 86400;
const DAYS = 30;

const DOMAINS = [
  {
    id: 1,
    domain: 'acme.com',
    policy: 'reject',
    pct: 100,
    spf: 'v=spf1 include:_spf.google.com include:sendgrid.net -all',
    // Daily volumes and pass rates per reporting org
    orgs: [
      { name: 'Google Inc.',      id: 'goog',  total: 180, passRate: 0.97, ip: '209.85.220.41',  from: 'mail.acme.com' },
      { name: 'Yahoo Inc.',       id: 'yahoo', total: 60,  passRate: 0.95, ip: '98.136.103.24',  from: 'mail.acme.com' },
      { name: 'Microsoft Corp.',  id: 'msft',  total: 40,  passRate: 0.96, ip: '40.107.20.90',   from: 'mail.acme.com' },
      { name: 'Apple Inc.',       id: 'aapl',  total: 15,  passRate: 0.98, ip: '17.57.8.200',    from: 'mail.acme.com' },
    ],
  },
  {
    id: 2,
    domain: 'getacme.com',
    policy: 'quarantine',
    pct: 50,
    spf: 'v=spf1 include:_spf.google.com ~all',
    orgs: [
      { name: 'Google Inc.',      id: 'goog',  total: 95,  passRate: 0.80, ip: '209.85.220.41',  from: 'mail.getacme.com' },
      { name: 'Yahoo Inc.',       id: 'yahoo', total: 30,  passRate: 0.77, ip: '98.136.103.24',  from: 'mail.getacme.com' },
      { name: 'SendGrid',         id: 'sg',    total: 25,  passRate: 0.72, ip: '167.89.0.15',    from: 'em.getacme.com' },
    ],
  },
  {
    id: 3,
    domain: 'acme-mail.com',
    policy: 'none',
    pct: 0,
    spf: 'v=spf1 +all',
    orgs: [
      { name: 'Google Inc.',      id: 'goog',  total: 45,  passRate: 0.45, ip: '209.85.220.41',  from: 'acme-mail.com' },
      { name: 'Yahoo Inc.',       id: 'yahoo', total: 18,  passRate: 0.42, ip: '98.136.103.24',  from: 'acme-mail.com' },
    ],
  },
];

const lines: string[] = [
  '-- InboxAngel demo seed — generated by scripts/seed-demo.ts',
  '-- Safe to re-run: uses INSERT OR IGNORE + ON CONFLICT',
  '',
  '-- Domains',
];

for (const d of DOMAINS) {
  lines.push(
    `INSERT OR IGNORE INTO domains (id, domain, rua_address, dmarc_policy, dmarc_pct, spf_record, dkim_configured, auth_record_provisioned, created_at, updated_at)`,
    `VALUES (${d.id}, '${d.domain}', 'rua@reports.inboxangel.io', '${d.policy}', ${d.pct}, '${d.spf}', 1, 1, ${NOW - 90 * DAY}, ${NOW});`,
  );
}

lines.push('', '-- Aggregate reports + records');

let reportId = 1;
let recordId = 1;

for (let dayOffset = DAYS - 1; dayOffset >= 0; dayOffset--) {
  const dayBegin = NOW - (dayOffset + 1) * DAY;
  const dayEnd   = NOW - dayOffset * DAY - 1;

  for (const d of DOMAINS) {
    for (const org of d.orgs) {
      // Small random-ish variation seeded by day + org to be deterministic
      const jitter = ((dayOffset * 7 + org.id.charCodeAt(0)) % 20) - 10; // -10..+9
      const total = Math.max(1, org.total + jitter);
      const passed = Math.round(total * org.passRate);
      const failed = total - passed;
      const rid = `${org.id}-${d.domain.replace(/\./g, '')}-${dayOffset}`;

      lines.push(
        `INSERT OR IGNORE INTO aggregate_reports (id, domain_id, org_name, report_id, date_begin, date_end, total_count, pass_count, fail_count, created_at)`,
        `VALUES (${reportId}, ${d.id}, '${org.name}', '${rid}', ${dayBegin}, ${dayEnd}, ${total}, ${passed}, ${failed}, ${NOW - dayOffset * DAY});`,
      );

      // 1–2 source records per report
      if (passed > 0) {
        lines.push(
          `INSERT OR IGNORE INTO report_records (id, report_id, source_ip, count, disposition, dkim_result, dkim_domain, spf_result, spf_domain, header_from, created_at)`,
          `VALUES (${recordId}, ${reportId}, '${org.ip}', ${passed}, '${d.policy}', 'pass', '${d.domain}', 'pass', '${d.domain}', '${org.from}', ${NOW - dayOffset * DAY});`,
        );
        recordId++;
      }

      if (failed > 0) {
        // Failing records come from a "suspicious" IP
        const badIp = `185.${(dayOffset % 200) + 10}.${(org.id.charCodeAt(0) % 200) + 10}.${(dayOffset % 100) + 1}`;
        lines.push(
          `INSERT OR IGNORE INTO report_records (id, report_id, source_ip, count, disposition, dkim_result, dkim_domain, spf_result, spf_domain, header_from, created_at)`,
          `VALUES (${recordId}, ${reportId}, '${badIp}', ${failed}, 'none', 'fail', '${d.domain}', 'fail', '${d.domain}', '${d.domain}', ${NOW - dayOffset * DAY});`,
        );
        recordId++;
      }

      reportId++;
    }
  }
}

lines.push('', `-- ${reportId - 1} reports, ${recordId - 1} records inserted`);

console.log(lines.join('\n'));
